---
swagger: 2.0
host: localhost:3000
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
info:
  title: Slot Machine API
  description: Simple Slot Machine API spike
  contact:
    name: Zak B. Elep
    url: https://github.com/yoyo-holdings/slot_spike
    email: zak.elep@yoyo-holdings.com
  version: 0.0.1
paths:
  /slots/start:
    any:
      x-mojo-controller: SlotSpike::Controller::Api
      operationId: startMachine
      summary: start the Slot Machine
      description: |
        This endpoint returns an array of numbers corresponding
        to the items/pictures to be shown on the slot machine.
        The response also includes an optional point amount.
      parameters:
        - name: user
          in: query
          description: The user ID.
          required: true
          type: string
      responses:
        200:
          description: The slot machine result.
          schema:
            $ref: '#/definitions/SlotMachineResult'
definitions:
  SlotMachineResult:
    properties:
      slots:
        type: array
        items:
          maxItems: 3
          type: integer
          description: |
            Array of integers corresponding to slot image
            locations.
      prize:
        type: integer
        default: 0
        description: The prize point awarded.
